### ISSUE TITLE
활성화 바랍니다.

### ISSUE THREAD

**Issue by moy8502** [eca21z/HelpDesk#107]
org: eca21c

repo: eca21c-00-00-20-moy8502

url: https://github.com/eca21c/eca21c-00-00-20-moy8502

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check org : eca21c (expecting eca21z)

**Comment by kangwonlee** [comment]
org: eca21z

repo: eca21c-00-00-20-moy8502

url: https://github.com/eca21z/eca21c-00-00-20-moy8502

@moy8502

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-00-00-20-moy8502
Processing request above
https://github.com/eca21z/eca21c-00-00-20-moy8502

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-00-00-20-moy8502
Success! Start your engine!
https://github.com/eca21z/eca21c-00-00-20-moy8502
