### ISSUE TITLE
활성화 바랍니다

### ISSUE THREAD

**Issue by junsang-cpf20d** [eca21z/HelpDesk#149]
org: eca21z

repo: eca21c-00-00-20-junsang-cpf20d

url: https://github.com/eca21z/eca21c-00-00-20-junsang-cpf20d

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-00-00-20-junsang-cpf20d
Processing request above
https://github.com/eca21z/eca21c-00-00-20-junsang-cpf20d

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-00-00-20-junsang-cpf20d
Success! Start your engine!
https://github.com/eca21z/eca21c-00-00-20-junsang-cpf20d
