### ISSUE TITLE
활성봐라바니다.

### ISSUE THREAD

**Issue by MinjunKimKPU** [eca21z/HelpDesk#155]
org: eca21z

repo: eca21c-00-20-20-MinjunKimKPU

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-00-20-20-MinjunKimKPU
Processing request above
https://github.com/eca21z/eca21c-00-20-20-MinjunKimKPU

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-00-20-20-MinjunKimKPU
Success! Start your engine!
https://github.com/eca21z/eca21c-00-20-20-MinjunKimKPU
