### ISSUE TITLE
활성화 부탁드립니다.

### ISSUE THREAD

**Issue by junsang-cpf20d** [eca21z/HelpDesk#158]
org: eca21z
repo: eca21c-10-10-00-junsang-cpf20d

https://github.com/eca21z/eca21c-10-10-00-junsang-cpf20d/commits/master

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-10-10-00-junsang-cpf20d
Processing request above
https://github.com/eca21z/eca21c-10-10-00-junsang-cpf20d

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-10-10-00-junsang-cpf20d
Success! Start your engine!
https://github.com/eca21z/eca21c-10-10-00-junsang-cpf20d
