### ISSUE TITLE
2018110012 김지수

### ISSUE THREAD

**Issue by jisuukimm** [eca21z/HelpDesk#2]
org: eca21z
rep: eca21c-00-00-10-jisuukimm

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Could not find the repo name

**Comment by jisuukimm** [comment]
org: eca21z
rep: eca21c-00-00-10-jisuukimm

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Could not find the repo name
