### ISSUE TITLE
활성화 바랍니다.

### ISSUE THREAD

**Issue by Hajun-cpf21c** [eca21z/HelpDesk#21]
org: eca21z

repo: eca21c-00-00-20-Hajun-cpf21c

url: https://github.com/eca21z/eca21c-00-00-20-Hajun-cpf21c

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-00-00-20-Hajun-cpf21c
Processing request above
https://github.com/eca21z/eca21c-00-00-20-Hajun-cpf21c

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-00-00-20-Hajun-cpf21c
Success! Start your engine!
https://github.com/eca21z/eca21c-00-00-20-Hajun-cpf21c
