### ISSUE TITLE
활성화 부탁드립니다.

### ISSUE THREAD

**Issue by jongry** [eca21z/HelpDesk#225]
https://github.com/eca21z/eca21c-10-10-00-jongry/commits/master

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Possibly not enough info

**Comment by jongry** [comment]
org: eca21z

repo: eca21c-10-10-00-jongry

url: https://github.com/eca21z/eca21c-10-10-00-jongry

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-10-10-00-jongry
Processing request above
https://github.com/eca21z/eca21c-10-10-00-jongry

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-10-10-00-jongry
Success! Start your engine!
https://github.com/eca21z/eca21c-10-10-00-jongry

**Comment by jongry** [comment]
org: eca21
repo: eca21c-10-10-02-jongry
https://github.com/eca21z/eca21c-10-10-02-jongry
