### ISSUE TITLE
활성화바라빈다.

### ISSUE THREAD

**Issue by MinjunKimKPU** [eca21z/HelpDesk#228]
org: eca21z

repo: eca21c-10-30-01-MinjunKimKPU

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-10-30-01-MinjunKimKPU
Processing request above
https://github.com/eca21z/eca21c-10-30-01-MinjunKimKPU

**Comment by kangwon-naver** [comment]
org: eca21z
repo: eca21c-10-30-01-MinjunKimKPU
Success! Start your engine!
https://github.com/eca21z/eca21c-10-30-01-MinjunKimKPU
